### ISSUE TITLE
Adding custum marker to google street view

### ISSUE THREAD

**Issue by alinscodes** [GastonZalba/ol-street-view#4]
Is it possible to add a marker to the street view just like in this example?

**jsfiddle**: http://jsfiddle.net/geocodezip/7mh5ac28/2/
**issue**: https://stackoverflow.com/questions/30684507/adding-a-custom-marker-to-google-street-view

It would be also nice to have an option to keep or remove the actual map when you go into street view mode!
Thanks

**Comment by GastonZalba** [comment]
Yes, i could add both options. I had to refactor part of the code so I could do everything together. I'll probably have it this week

**Comment by alinscodes** [comment]
That would be good. Looking forward to it.

**Comment by GastonZalba** [comment]
Hi, new version 2.0.0 is ready. 
- See the [example](https://github.com/GastonZalba/ol-street-view/blob/master/examples/basic.js) to add a marker in the map and in the panorama
- Set `defaultMapSize: 'hidden'` to remove the map on street view mode

This version has some breaking changes. You need now to add the streetView instance as a control to the ol map:
`var streetView = new StreetView(opt_options);`
`map.addControl(streetView);`

**Comment by alinscodes** [comment]
that works fine although for the _refreshMap function I added the height of 100% to the map id element.
I also found it useful to add style to the button for streetview, I guess you can add that if you want to options too, so you can change the position, background color.


A nice to have too is not opening streetview if no images are found just like on google maps.
