### ISSUE TITLE
Google Maps JavaScript API loaded multiple

### ISSUE THREAD

**Issue by abydahana** [GastonZalba/ol-street-view#6]
Hello,
Do you have an option to prevent load the Google Maps JavaScript API twice? I have another module that is require the GMaps API. Since your module doesn't separate the load of GMaps API, it's throwing the errors like "`You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`".

Maybe you can give the exception to load the GMaps API when it's not yet loaded.

Thanks

**Comment by GastonZalba** [comment]
Hi, yes, i can add an attribute to prevent the autoload. I think I can do it this weekend.

**Comment by GastonZalba** [comment]
Check the 2.0.4 version and let me know. You have to pass `autoLoadLibrary: false` and run the `init` method manually -after- the GMaps library is available.

**Comment by GastonZalba** [comment]
@abydahana closing this. Feel free to reopen another issue if the problem persists.
