### ISSUE TITLE
Support for Web Components

### ISSUE THREAD

**Issue by cristianmadularu** [GastonZalba/ol-street-view#8]
Hi, 

I noticed that when trying to run the Street View in a Web Component, the related controls would not render properly. Uppon investigations, I noticed that the code lib code is making use of the 'document.body' in order to add/remove certain classes. That would not work when running in a Web Component due to the way the Shadow DOM works.

I noticed that, when initializing the library, there is an optional 'target' property which could be set. I beelive that, if set, the library should use this instead of 'document.body'.

I fixed locally the problem by simply checking if the target was set and, if it was set, I was using it instead of the 'document.body'. 

If you are ok with this, I would not mind creating a PR to update the current code base in case other people need it? (It would also allow me to not use a locally modified version :)).

Thanks! (and thank you for creating this great lib!)

**Comment by GastonZalba** [comment]
Hi, reviewing the code, I think maybe the correct approach should be in most cases to add those classes in the container created by the lib and not pollute the document body at all... And I think (maybe i'm wrong, i can't test it right now) that if you add all the classes to the target some extra buttons will not work/be displayed correctly because the target might not be its parent element. 

I never worked with Web Components, so if you can send me a small example to recreate the problem would be nice! We can make it work to all the cases.

Thanks!

**Comment by cristianmadularu** [comment]
I will try to create an example so we can use it to showcase the issue and also test the possible fix. Until then the only changes that I had to do were these:
1. create a 'target' field which points to 'document.body' by default or to the 'target' configured property if one was provided.
2. Update all the usages of 'document.body' with 'this.target'.
![image](https://github.com/GastonZalba/ol-street-view/assets/124408005/e1dda785-e0b4-4957-a4a4-5941d57413df)
3. I also copied/pasted all the styles into my web component - I am not sure if that was the best way (probbaly not), but I was not sure how else to get the styles it needed.

**Comment by GastonZalba** [comment]
I made some fixes and removed all the document.body references in [this branch](https://github.com/GastonZalba/ol-street-view/tree/8-support-for-web-components). If you can try it with your current configuration that would be great!

**Comment by cristianmadularu** [comment]
I have copied/pasted the contents of the ol-street-view.ts file in my local copy and gave it a try. It works very well! :) Thank you!

Not related to this problem, I have encontered another issue which I do not think it is related to WebComponents. In my application, we support layouts. Basically the user can select from a set of preconfigured layouts. All of these have map control (with StreetView enabled). Each time I load a layout, I get an additional Pegman control. The previous one does not seem to be disposed. I have a tried a number of tricks in order to make it go away without success. I even updated the code in order to not register any mouse events (since they do not seem to be removed on destroy) and that still did not solve it.
I am still trying different things, but, if you have any ideas on how to remove it, please let me know and I can try :)

For example, this is after changing the layout twice
<img width="179" alt="image" src="https://github.com/GastonZalba/ol-street-view/assets/124408005/686fb33c-3737-4088-b31f-0fa4c7fccd79">


Thank you again! :)

**Comment by cristianmadularu** [comment]
Also, here is a little bug I found in the newer version. While displaying the Street View, the initial Pegman is still visible
<img width="209" alt="image" src="https://github.com/GastonZalba/ol-street-view/assets/124408005/b8b53b6e-3b40-49c2-8aec-a81121306b8f">

**Comment by GastonZalba** [comment]
> Also, here is a little bug I found in the newer version. While displaying the Street View, the initial Pegman is still visible <img alt="image" width="209" src="https://private-user-images.githubusercontent.com/124408005/306060585-b8b53b6e-3b40-49c2-8aec-a81121306b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzI3ODIsIm5iZiI6MTcwODM3MjQ4MiwicGF0aCI6Ii8xMjQ0MDgwMDUvMzA2MDYwNTg1LWI4YjUzYjZlLTNiNDAtNDljMi04YWVjLWE4MTEyMTMwNmI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxOTU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmIzOTAyNTE0M2MwNmRiZGIyNWM3NmNkYWU1OTVmZjg0YTEyMmViNTlmMDAyNzMyMGY5NDRlNmU2NzEzMGU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V1V8P9iTsrZWisES7AGhuvKPNzT1n7_TOojR-VDYYa4">

I think maybe you've set a target and the element it's outside the open layers map (and the parent CSS class doesn't affect it now). The "correct" way will be to remove your current "target" setting and let the control be displayed on the map, next to the other open layers controls. Anyway, now I'm going to review the code (also to check the duplicate controls bugs) and make it hide even when the target is outside the map container.

**Comment by GastonZalba** [comment]
Already updated again the same branch with (I think) everything fixed. Check it if you can. In the coming days I will do a final review and publish

**Comment by cristianmadularu** [comment]
I got the latest and tried it. everything looks good except my reload issue where the pegmen gets duplicated (and the drap&drop borken).
I can detect then the compoenents get destroyed and tried calling a number on things on the streetview (like setMap(null)), playing with the mouse hanlders, etc., but i can't get it to work well after a layout change.

**Comment by GastonZalba** [comment]
In this version using the same instance of the control it works correctly for me by first doing a setMap(null) to remove everything, and setMap(newMapInstance) to reassign it. But from what you tell me, you must be creating a new instance both on the map and in the control. I didn't try that. Keep in mind that doing this it will load the Google Maps library twice, so you might want to load it separately using `autoLoadGoogleMaps: false` and will be less efficient because it has to recreate all the dom elements every time (and maybe consume more api calls $ to prepare the services for the panorama?). 

I don't know what your project is like, but if I were you I would try to create just one instance of each and maybe change the map target to the new div/layout. EDIT: I don't know if it would work now or if I would have to make more adjustments to this library

In any case, I'm going to try to make it work in this cases too!

**Comment by GastonZalba** [comment]
Hi, here again. New version, same branch. Alredy tested the creation of more than one instance and it seems to work well in my configuration (and fixed the maps library autoloading more than once in those cases). Remember to setMap(null) in the previous instance to remove listeners, buttons and so. After that, you could reassign the control to a new map with setMap(newMap) or create a new instance of the control. It should work in both cases. Let me know if it works now. Fingers crossed.

**Comment by cristianmadularu** [comment]
Awesome, trying it now! Stand by :)

**Comment by cristianmadularu** [comment]
OK great news! It works like a charm. I did not even have to set the target element when initializing it and setting the map to null when unloading also worked very well now.

From my point of view, everything works great!

Thank you so much! :)

**Comment by cristianmadularu** [comment]
Btw, any plans to merge to main and release a new version?
Thanks

**Comment by GastonZalba** [comment]
Maybe tomorrow. Busy days

**Comment by cristianmadularu** [comment]
No rush, thank you!

**Comment by GastonZalba** [comment]
Finally, merged with main and pushed to npm!

**Comment by cristianmadularu** [comment]
> Finally, merged with main and pushed to npm!

Wonderful, 
Thank you again!
