### ISSUE TITLE
Default usage written in readme doesn't work on mobile

### ISSUE THREAD

**Issue by Mysterius** [GastonZalba/ol-street-view#9]
Hello,

Just a heads up to say that the default code that is written below "Usage" on the readme works... but not on mobile (you cannot drag the pegman, it immediately launches street view to where you just clicked). It works on PC though.

However, the code that you used [in the "Basic" example](https://raw.githack.com/GastonZalba/ol-street-view/v2.2.3/examples/basic.html) works just fine.

I'm not sure why, sorry ^^'

**Comment by GastonZalba** [comment]
Hi, thanks for the report. It's because of the `target: 'map'` parameter (needed for ol 5). I'm gonna remove that from the readme because that version is already very old.
